apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node5-deployment
  name: node5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node5-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node5-pod
    spec:
      volumes:
        - name: my-disk
          emptyDir: {}
        - name: http-request-uri
          secret:
            secretName: http-request-uri-node5
            items:
              - key: http-request-uri
                path: http-request-uri
      containers:
        - image: docker.io/asmiwdtc/peerservice
          imagePullPolicy: Always
          name: node5-container
          command: ["java", "-jar", "/app/app.jar"]
          envFrom:
            - configMapRef:
                name: node5-config
                optional: false
          volumeMounts:
            - name: my-disk
              mountPath: /my-data
            - name: http-request-uri
              mountPath: /my-config
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
