apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node3-deployment
  name: node3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node3-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node3-pod
    spec:
      volumes:
        - name: my-disk
          emptyDir: {}
        - name: http-request-uri
          secret:
            secretName: http-request-uri
            items:
              - key: http-request-uri-node3
                path: http-request-uri
        - name: database-config
          secret:
            secretName: dbinfo
            items:
              - key: db-url
                path: db-url
              - key: db-username
                path: db-username
              - key: db-password
                path: db-password
              - key: table-node3
                path: db-table
      containers:
        - image: docker.io/asmiwdtc/peerservice
          imagePullPolicy: Always
          name: node3-container
          command: ["java", "-jar", "/app/app.jar"]
          envFrom:
            - configMapRef:
                name: node3-config
                optional: false
          volumeMounts:
            - name: my-disk
              mountPath: /my-data
            - name: http-request-uri
              mountPath: /my-config
            - name: database-config
              mountPath: /db-config
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}