apiVersion: v1
kind: ConfigMap
metadata:
  name: node5-config
data:
  CHORD_DEGREE: "12"
  CHORD_HOSTNAME: node5
  CHORD_FIRST_NODE: "false"
  RMI_PORT: "1099"
  CHORD_JOIN_NODE_HOSTNAME: node4
  CHORD_JOIN_NODE_PORT: "1099"
  NOTIFICATION_NAME: los_angeles_weather
  HTTP_REQUEST_FILE_LOCATION: "/my-config/http-request-uri"
  HTTP_REQUEST_PERIOD: "5000"