apiVersion: v1
kind: ConfigMap
metadata:
  name: node1-config
data:
  CHORD_DEGREE: "12"
  CHORD_HOSTNAME: node1
  CHORD_FIRST_NODE: "true"
  RMI_PORT: "1099"
  NOTIFICATION_NAME: eth_price
  HTTP_REQUEST_FILE_LOCATION: "/my-config/http-request-uri"
  HTTP_REQUEST_PERIOD: "20000"

