apiVersion: v1
kind: ConfigMap
metadata:
  name: node3-config
data:
  CHORD_DEGREE: "12"
  CHORD_HOSTNAME: node3
  CHORD_FIRST_NODE: "false"
  RMI_PORT: "1099"
  CHORD_JOIN_NODE_HOSTNAME: node2
  CHORD_JOIN_NODE_PORT: "1099"
  NOTIFICATION_NAME: binance_price
  HTTP_REQUEST_FILE_LOCATION: "/my-config/http-request-uri"
  HTTP_REQUEST_PERIOD: "20000"