apiVersion: v1
kind: ConfigMap
metadata:
  name: database-env
data:
  DB_URL_FILE_LOCATION: "/db-config/db-url"
  DB_USERNAME_FILE_LOCATION: "/db-config/db-username"
  DB_TABLE_FILE_LOCATION: "/db-config/db-table"
  DB_PASSWORD_FILE_LOCATION: "/db-config/db-password"

