apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: node1
    app: node-1-pod
  name: node-1-pod
spec:
  volumes:
    - name: my-disk
      emptyDir:
        {}
        #gcePersistentDisk:
        #  pdName: my-disk
        #  fsType: ext4
        #emptyDir: {}
        #sizeLimit:
  containers:
    - image: docker.io/asmiwdtc/chordpubsubnode
      imagePullPolicy: Always
      name: node-1-pod-container
      command: ["java", "-jar", "/app/app.jar"]
      env:
        - name: CHORD_DEGREE
          value: "12"
        - name: CHORD_HOSTNAME
          value: "node1"
        - name: CHORD_FIRST_NODE
          value: "true"
        - name: RMI_PORT
          value: "1099"
      volumeMounts:
        - name: my-disk
          mountPath: /my-data
      resources: {}
  #    livenessProbe:
  #      httpGet:
  #        path: /
  #        port: 11533
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
