apiVersion: v1
kind: ConfigMap
metadata:
  name: node2-config
data:
  CHORD_DEGREE: "12"
  CHORD_HOSTNAME: node2
  CHORD_FIRST_NODE: "false"
  RMI_PORT: "1099"
  CHORD_JOIN_NODE_HOSTNAME: node1
  CHORD_JOIN_NODE_PORT: "1099"